### ISSUE TITLE
Grammar updates needed?

### ISSUE THREAD

**Issue by Nhawdge** [jnavila/git-manpages-l10n#40]
While trying to better understand `git update-index` I found this line `The way git update-index handles files it is told about can be modified using the various options:` It doesn't read correctly, but I'm no expert to fix it. Thanks!

https://github.com/jnavila/git-manpages-
l10n/blob/a281eebe993f24150e3393638c08fc43cdd9d792/en/git-update-index.txt#L39

**Comment by jnavila** [comment]
This repository is focused on the translation of the manpages from english to other languages. The english original version is pulled from the [git project itself](https://git-scm.com/community) where updates and fixups are performed on the source of the manpages.

The git project is managed via a mailing list git@vger.kernel.org where you can send issues and  patches (which are always better welcome instead of issue reports).
