### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ttdly** [jnavila/git-manpages-l10n#77]
Hello,
I found some mistakes when translating the document:
- [Tins page](https://git-scm.com/docs/gitglossary/en) only have English version,and the others are show :"Warning | Missing **/glossary-content.txt   See original version for this content."
- [This page](https://git-scm.com/docs/gitattributes), I can't find the source file in the Weblate platform.

**Comment by jnavila** [comment]
Hello,

Not all files of git documentation have been selected for translation. This is on purpose, because the volume of documentation to translate would be very important. You can find the list of included files [here](https://github.com/jnavila/git-manpages-l10n/blob/master/sources.txt). 

This is on purpose, to help translators focus on higher priority content and not be overwelmed by the volume of text. Most common commands are available for translation. More technical information is limited for the moment. 

I plan to make a specific translation package containing the advanced information of the pages.

**Comment by ttdly** [comment]
Ok, thanks for your reply.
>I plan to make a specific translation package containing the advanced information of the pages.

It seems we all have a lot of work to do. :-)
